DATA_SOURCE = 'https://d37ci6vzurychx.cloudfront.net/trip-data/yellow_tripdata_2022-02.parquet'
DATA_SOURCE = 'data/yellow_tripdata_2022-01.parquet'
FEATURE_GROUP_NAME = 'taxi_demand_hourly'
FEATURE_GROUP_DESCRIPTION = "Hourly Taxi Demand hourly sampled"
API_KEY_HOPSWORKS = 'iS9O9H01oRxEzuHI.YMzWi2ap65sQZqqoZR6tO8PICrbPwl0zCuP94bqX1miHK2m66EkcPEZwMWY88wTk'
FEATURE_DESCRIPTIONS = [
    {"name": "timestamp", "description": "Timestamp indicating the time of observation"},
    {"name": "taxi_demand", "description": "Demand for taxis at the specified timestamp"},
    {"name": "passenger_demand",
        "description": "Demand for passengers at the specified timestamp"},
    {"name": "timestamp_month", "description": "Month extracted from the timestamp"},
    {"name": "timestamp_quarter",
        "description": "Quarter of the year extracted from the timestamp"},
    {"name": "timestamp_semester",
        "description": "Semester of the year extracted from the timestamp"},
    {"name": "timestamp_week",
        "description": "Week of the year extracted from the timestamp"},
    {"name": "timestamp_day_of_week",
        "description": "Day of the week extracted from the timestamp"},
    {"name": "timestamp_day_of_month",
        "description": "Day of the month extracted from the timestamp"},
    {"name": "timestamp_day_of_year",
        "description": "Day of the year extracted from the timestamp"},
    {"name": "timestamp_weekend",
        "description": "Indicates whether the timestamp is on a weekend (yes/no)"},
    {"name": "timestamp_month_start",
        "description": "Indicates whether the timestamp is the start of the month (yes/no)"},
    {"name": "timestamp_month_end",
        "description": "Indicates whether the timestamp is the end of the month (yes/no)"},
    {"name": "timestamp_quarter_start",
        "description": "Indicates whether the timestamp is the start of the quarter (yes/no)"},
    {"name": "timestamp_quarter_end",
        "description": "Indicates whether the timestamp is the end of the quarter (yes/no)"},
    {"name": "timestamp_year_start",
        "description": "Indicates whether the timestamp is the start of the year (yes/no)"},
    {"name": "timestamp_year_end",
        "description": "Indicates whether the timestamp is the end of the year (yes/no)"},
    {"name": "timestamp_hour",
        "description": "Hour of the day extracted from the timestamp"},
    {"name": "passenger_demand_lag_1",
        "description": "Demand for passengers lagged by 1 timestamp"},
    {"name": "taxi_demand_lag_1", "description": "Demand for taxis lagged by 1 timestamp"},
    {"name": "passenger_demand_lag_2",
        "description": "Demand for passengers lagged by 2 timestamps"},
    {"name": "taxi_demand_lag_2",
        "description": "Demand for taxis lagged by 2 timestamps"},
    {"name": "passenger_demand_lag_4",
        "description": "Demand for passengers lagged by 4 timestamps"},
    {"name": "taxi_demand_lag_4",
        "description": "Demand for taxis lagged by 4 timestamps"},
    {"name": "passenger_demand_lag_8",
        "description": "Demand for passengers lagged by 8 timestamps"},
    {"name": "taxi_demand_lag_8",
        "description": "Demand for taxis lagged by 8 timestamps"},
    {"name": "passenger_demand_lag_16",
        "description": "Demand for passengers lagged by 16 timestamps"},
    {"name": "taxi_demand_lag_16",
        "description": "Demand for taxis lagged by 16 timestamps"},
    {"name": "passenger_demand_lag_24",
        "description": "Demand for passengers lagged by 24 timestamps"},
    {"name": "taxi_demand_lag_24",
        "description": "Demand for taxis lagged by 24 timestamps"},
    {"name": "passenger_demand_window_24_mean",
        "description": "Mean demand for passengers in a window of 24 timestamps"},
    {"name": "taxi_demand_window_24_mean",
        "description": "Mean demand for taxis in a window of 24 timestamps"},
]

TABLE_NAME = 'uber-texi-demand-hourly'
# AWS credentials
AWS_ACCESS_KEY_ID = 'AKIA6EQMX6OHIBMJEPUZ'
AWS_SECRET_ACCESS_KEY = '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'
MODEL_NAME = 'uber-taxi-demand-hourly'